default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: service_status_development

test:
  <<: *default
  database: service_status_test

production:
  <<: *default
  database: service_status_produciton
